module.exports = [
  {
    "pointOfContact": "Hirut Tesfaye",
    "role": "",
    "location": "Alabama",
    "email": "hirutasfaw@hotmail.com",
    "phoneNumber": "",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "DR.Gebeyehu Ejigu",
    "role": "President",
    "location": "Arizona",
    "email": "ecaa3board@gmail.com",
    "phoneNumber": "708.6420816",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Merid Alemayehu",
    "role": "President",
    "location": "Atlanta",
    "email": "staff@ethiopiancaa.org",
    "phoneNumber": "7706395532",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Yoftahe",
    "role": "Executive Board",
    "location": "Boston",
    "email": "theyoftaheshow@gmail.com",
    "phoneNumber": "",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Aklilu Adeye",
    "role": "",
    "location": "Chicago",
    "email": "info@ecachicago.org",
    "phoneNumber": "",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Samuel Gebremichael /Mesfin",
    "role": "",
    "location": "Colorado",
    "email": "sam@ethioco.org",
    "phoneNumber": "720.388.7860",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Mahadere Endale",
    "role": "Executive Director",
    "location": "Connecticut",
    "email": "contact@ecact.org",
    "phoneNumber": "860.794.1960",
    "website": "https://ecact.org/",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "",
    "role": "",
    "location": "DC",
    "email": "info@ecdcus.org",
    "phoneNumber": "",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Zekarias Felege",
    "role": "President",
    "location": "Kansas City",
    "email": "zekarias.felege@ecokc.org",
    "phoneNumber": "",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Yodit Dori",
    "role": "",
    "location": "Kentucky",
    "email": "Yoditdori@hotmail.com",
    "phoneNumber": "5027419460",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Hirout Dagnew",
    "role": "",
    "location": "Los Angeles",
    "email": "info@eclosangeles.org",
    "phoneNumber": "",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Anteneh",
    "role": "",
    "location": "Maryland",
    "email": "Ethiopiancommunitym@gmail.com",
    "phoneNumber": "240.839.7805",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "",
    "role": "",
    "location": "Massachusetts",
    "email": "info@mesaboston.org",
    "phoneNumber": "240.839.7805",
    "website": "https://www.mesaboston.com/",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Esuendale Gashaw",
    "role": "",
    "location": "Minnesota",
    "email": "esuendaleg@gmail.com",
    "phoneNumber": "",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Gedlu Metafaria",
    "role": "",
    "location": "Missouri (St. Louis)",
    "email": "Gejigu@govst.edu",
    "phoneNumber": "314.305.6036",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Ayanaw",
    "role": "",
    "location": "Nashville Tennessee",
    "email": "contactus@ecantn.org",
    "phoneNumber": "",
    "website": "http://www.ecantn.org/",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "",
    "role": "",
    "location": "New York",
    "email": "ecmaany@gmail.com",
    "phoneNumber": "",
    "website": "https://www.ecmaany.org/",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Nuria/Yonas ",
    "role": "President",
    "location": "North Carolina",
    "email": "Nuria.Adem99@gmail.com",
    "phoneNumber": "206.910.6095",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Minilik Andarge",
    "role": "",
    "location": "Oakland",
    "email": "ethiopiancommunityoakland@gmail.com",
    "phoneNumber": "",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Yonas Kassie",
    "role": "Executive Director",
    "location": "Oregon",
    "email": "yonask@eecrc.org",
    "phoneNumber": "503 462 9806",
    "website": "http://eecrc.org/",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Huda Yusuf",
    "role": "",
    "location": "Oregon",
    "email": "huday@eecrc.org",
    "phoneNumber": "",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Hiwot Bekele",
    "role": "",
    "location": "Oregon",
    "email": "hiwotb@eecrc.org",
    "phoneNumber": "",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Adiyam",
    "role": "",
    "location": "Oregon",
    "email": "info@eecrc.org",
    "phoneNumber": "",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Abebe Wodaje",
    "role": "",
    "location": "Sacramento",
    "email": "eccsacto@gmail.com",
    "phoneNumber": "",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Sophia Benalfew",
    "role": "",
    "location": "Seattle",
    "email": "sophiab@ecseattle.org",
    "phoneNumber": "",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Dawit Alemu",
    "role": "",
    "location": "South Carolina",
    "email": "DawitAlemu83@gmail.com",
    "phoneNumber": "8034462997",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Addis",
    "role": "",
    "location": "Texas",
    "email": "ethiocomdallas@gmail.com",
    "phoneNumber": "214.321.9992",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  },
  {
    "pointOfContact": "Tekele",
    "role": "",
    "location": "Toronto",
    "email": "Tekle@tekle.net",
    "phoneNumber": "",
    "website": "",
    "associationName": "Community Association",
    "description": "North America based Ethiopian organization",
  }
];